name: Ansible run
description: Reusable Ansible action for GitHub workflows
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/ssh
      with:
        SSH_PRIVATE_KEY_ANSIBLE: ${{ inputs.SSH_PRIVATE_KEY_ANSIBLE }}    

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Ansible & proxmox requirements
      run: |
        pip install ansible "proxmoxer>=2.0" requests netaddr
      shell: bash

    - name: Install Ansible collections
      run: ansible-galaxy collection install -r ./ansible/requirements.yml
      shell: bash

    - name: Run Ansible playbook
      working-directory: "${{ inputs.working-directory}}"
      run: ansible-playbook ./playbooks/managed.yml -l 'managed'
      shell: bash

inputs:
  working-directory:
    description: "Working directory for Ansible playbook"
    required: true
  SSH_PRIVATE_KEY_ANSIBLE:
    description: "SSH private key for Ansible"
    required: true
    secret: true
