plugin: community.proxmox.proxmox
url: "{{ lookup('env', 'PROXMOX_URL') }}"
user: "{{ lookup('env', 'PROXMOX_USER') }}"
token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
want_facts: true
want_proxmox_nodes: true
keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group
groups:
  notmanaged: "'notmanaged' in (proxmox_tags_parsed|list)"
  managed: "'managed' in (proxmox_tags_parsed|list)"
  docker-host: "'docker-host' in (proxmox_tags_parsed|list)"
  # ansible-playbook ping_test.yml -l 'all:!notmanaged'