---
- name: Apply roles
  hosts: all
  remote_user: ansible
  become: true
  roles:
    - set_timezone
    - ansible_user
    - role: install_packages
      when: ansible_facts['distribution'] == 'Ubuntu' 
    - role: unattended_upgrades
      when: ansible_facts['distribution'] == 'Ubuntu'
- name: Import kube cluster playbook
  ansible.builtin.import_playbook: k3s.orchestration.site
