---
- name: Import managed infrastructure
  ansible.builtin.import_playbook: managed.yml
  tags: 
    - managed
  
- name: Apply roles
  hosts: all
  remote_user: ansible
  become: true
  roles:
    - vault
