name: Setup WireGuard
description: Reusable WireGuard setup action for GitHub workflows
runs:
  using: "composite"
  steps:
    - run: sudo apt install wireguard
      shell: bash

    - run: echo "${{ inputs.WIREGUARD_PRIVATE_KEY }}" > privatekey
      shell: bash

    - run: |
        sudo ip link add dev wg0 type wireguard
        sudo ip address add dev wg0 "${{ inputs.RUNNER_IP }}" peer "${{ inputs.PEER_IP }}"
        sudo wg set wg0 listen-port 48123 private-key privatekey peer "${{ inputs.WIREGUARD_PEER_PUBLIC_KEY }}" allowed-ips 0.0.0.0/0 endpoint "${{ inputs.WIREGUARD_ENDPOINT }}"
        sudo ip link set up dev wg0
        sudo ip route add 10.0.0.0/24 dev wg0
      shell: bash

    - run: |
        sudo resolvectl dns wg0 "${{ inputs.PEER_IP }}"
        sudo resolvectl domain wg0 ~.
      shell: bash
    # - run: |
    #     ping -c 4 "${{ inputs.PEER_IP }}"
    #     ping -c 4 "${{ inputs.PVE_HOST }}"
    #   shell: bash

inputs:
  WIREGUARD_PRIVATE_KEY:
    description: "WireGuard private key"
    required: true
  RUNNER_IP:
    description: "IP address for the GitHub runner"
    required: true
  PEER_IP:
    description: "IP address of the WireGuard peer"
    required: true
  WIREGUARD_PEER_PUBLIC_KEY:
    description: "WireGuard peer public key"
    required: true
  WIREGUARD_ENDPOINT:
    description: "WireGuard peer endpoint (IP:port)"
    required: true
