name: Ansible run

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "ansible/**"
  # workflow_run:
  #   workflows: ["Terraform Actions"]
  #   types:
  #     - completed
jobs:
  run:
    name: Ansible run
    runs-on: ubuntu-latest
    environment: proxmox-rw
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/wireguard
        with:
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          RUNNER_IP: ${{ secrets.RUNNER_IP }}
          PEER_IP: ${{ secrets.PEER_IP }}
          WIREGUARD_PEER_PUBLIC_KEY: ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }}
          WIREGUARD_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}
      
      - uses: ./.github/actions/ansible
        env:
          PROXMOX_USER: ${{ secrets.PROXMOX_USER_ANSIBLE }}
          PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID_ANSIBLE }}
          PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_SECRET_ANSIBLE }}
          PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
        with:
          working-directory: ansible
          SSH_PRIVATE_KEY_ANSIBLE: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}

      # - name: Run Ansible playbook for k3s hosts
      #   working-directory: ./ansible
      #   run: ansible-playbook k3s.orchestration.site -i ./inventory/k3s.inventory.yml
