name: Terraform Deploy

on:
  workflow_dispatch: 

jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: proxmox-ro
    env: &common-env
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
      PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID }}
      PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_SECRET }}
      PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
      TF_VAR_virtual_environment_endpoint: ${{ secrets.TF_VAR_VIRTUAL_ENVIRONMENT_ENDPOINT }}
      TF_VAR_virtual_environment_ssh_username: ${{ secrets.TF_VAR_VIRTUAL_ENVIRONMENT_SSH_USERNAME }}
      TF_VAR_virtual_environment_api_token: ${{ secrets.TF_VAR_VIRTUAL_ENVIRONMENT_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - uses: ./.github/actions/wireguard
        with: &wireguard-env
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          RUNNER_IP: ${{ secrets.RUNNER_IP }}
          PEER_IP: ${{ secrets.PEER_IP }}
          WIREGUARD_PEER_PUBLIC_KEY: ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }}
          WIREGUARD_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}
          PVE_HOST: ${{ secrets.PVE_HOST }}

      - uses: ./.github/actions/ssh
        with:
          RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
          PVE_HOST: ${{ secrets.PVE_HOST }}

      - run: terraform init
        working-directory: ./terraform/infrastructure/images

      - name: Plan
        run: terraform plan -lock=false --input=false -var-file=../../environments/images/homelab.tfvars
        working-directory: ./terraform/infrastructure/images      

  apply:
    name: "Terraform Apply"
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: plan
    runs-on: ubuntu-latest
    environment: proxmox-rw
    env: *common-env
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: ./.github/actions/wireguard
        with: *wireguard-env

      - uses: ./.github/actions/ssh
        with:
          RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
          PVE_HOST: ${{ secrets.PVE_HOST }}

      - run: terraform init
        working-directory: ./terraform/infrastructure/images

      - name: Apply
        run: terraform apply -auto-approve --input=false -var-file=../../environments/images/homelab.tfvars
        working-directory: ./terraform/infrastructure/images

