name: Terraform plan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: proxmox-ro
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
      PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID }}
      PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_SECRET }}
      PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
      TF_VAR_VIRTUAL_ENVIRONMENT_ENDPOINT: ${{ secrets.VIRTUAL_ENVIRONMENT_ENDPOINT }}
      TF_VAR_VIRTUAL_ENVIRONMENT_SSH_USERNAME: ${{ secrets.VIRTUAL_ENVIRONMENT_SSH_USERNAME }}
      TF_VAR_VIRTUAL_ENVIRONMENT_API_TOKEN: ${{ secrets.VIRTUAL_ENVIRONMENT_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - uses: ./.github/actions/wireguard
        with:
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          RUNNER_IP: ${{ secrets.RUNNER_IP }}
          PEER_IP: ${{ secrets.PEER_IP }}
          WIREGUARD_PEER_PUBLIC_KEY: ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }}
          WIREGUARD_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}
          PVE_HOST: ${{ secrets.PVE_HOST }}

      - uses: ./.github/actions/ssh
        with:
          RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
          PVE_HOST: ${{ secrets.PVE_HOST }}

      - run: terraform init
        working-directory: ./terraform/infrastructure/compute

      - run: terraform plan --input=false -var-file=../../environments/compute/homelab.tfvars
        id: plan
        working-directory: ./terraform/infrastructure/compute

      - name: Update PR Comment
        uses: actions/github-script@v7
        with:
          script: |
            const output = `#### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>

            \`\`\`terraform
            ${{ steps.plan.outputs.stdout }}
            \`\`\`

            </details>`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
  apply:
    name: "Terraform Apply"
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: proxmox-rw
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
      PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID }}
      PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_SECRET }}
      PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
      TF_VAR_VIRTUAL_ENVIRONMENT_ENDPOINT: ${{ secrets.VIRTUAL_ENVIRONMENT_ENDPOINT }}
      TF_VAR_VIRTUAL_ENVIRONMENT_SSH_USERNAME: ${{ secrets.VIRTUAL_ENVIRONMENT_SSH_USERNAME }}
      TF_VAR_VIRTUAL_ENVIRONMENT_API_TOKEN: ${{ secrets.VIRTUAL_ENVIRONMENT_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: ./.github/actions/wireguard
        with:
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          RUNNER_IP: ${{ secrets.RUNNER_IP }}
          PEER_IP: ${{ secrets.PEER_IP }}
          WIREGUARD_PEER_PUBLIC_KEY: ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }}
          WIREGUARD_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}
          PVE_HOST: ${{ secrets.PVE_HOST }}

      - uses: ./.github/actions/ssh
        with:
          RUNNER_SSH_KEY: ${{ secrets.RUNNER_SSH_KEY }}
          PVE_HOST: ${{ secrets.PVE_HOST }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
