name: Terraform Actions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment to deploy (e.g., compute, talos)"
        required: true
        type: choice
        options:
          - compute
          - talos
      destroy:
        description: "Destroy resources"
        required: true
        default: false
        type: boolean
  pull_request:
    branches: [main]
    paths: &paths
      - 'terraform/modules/**'
      - 'terraform/infrastructure/**'
      - 'terraform/environments/**'
      - '.github/actions/**'
      - '.github/workflows/terraform.yml'
  push:
    branches: [main]
    paths: *paths
jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [compute]
    outputs:
      plan-success: ${{ steps.plan.outputs.success }}
    environment: proxmox-ro
    env: &common-env
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
      PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID }}
      PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_SECRET }}
      PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
      TF_VAR_virtual_environment_endpoint: ${{ secrets.TF_VAR_VIRTUAL_ENVIRONMENT_ENDPOINT }}
      TF_VAR_virtual_environment_ssh_username: ${{ secrets.TF_VAR_VIRTUAL_ENVIRONMENT_SSH_USERNAME }}
      TF_VAR_virtual_environment_api_token: ${{ secrets.TF_VAR_VIRTUAL_ENVIRONMENT_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - uses: ./.github/actions/wireguard
        with: &wireguard-env
          WIREGUARD_PRIVATE_KEY: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          RUNNER_IP: ${{ secrets.RUNNER_IP }}
          PEER_IP: ${{ secrets.PEER_IP }}
          WIREGUARD_PEER_PUBLIC_KEY: ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }}
          WIREGUARD_ENDPOINT: ${{ secrets.WIREGUARD_ENDPOINT }}

      - run: terraform init
        working-directory: ./terraform/infrastructure/${{ matrix.environments }}

      - name: Plan
        run: terraform plan -lock=false --input=false -var-file=../../environments/${{ matrix.environments }}/homelab.tfvars ${{ inputs.destroy == true && '-destroy' || '' }}

        id: plan
        working-directory: ./terraform/infrastructure/${{ matrix.environments }}

  apply:
    name: "Terraform Apply"
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [compute]
    environment: proxmox-rw
    env: *common-env
    
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: ./.github/actions/wireguard
        with: *wireguard-env

      - run: terraform init
        working-directory: ./terraform/infrastructure/${{ matrix.environments }}

      - name: ${{ inputs.destroy == true && 'Destroy' || 'Apply' }}
        env: 
          PROXMOX_VE_SSH_PRIVATE_KEY: ${{ secrets.PROXMOX_VE_SSH_PRIVATE_KEY }}
        run: terraform ${{ inputs.destroy == true && '-destroy' || '' }} -auto-approve --input=false -var-file=../../environments/${{ matrix.environments }}/homelab.tfvars
        working-directory: ./terraform/infrastructure/${{ matrix.environments }}
